# Outlier Analysis

In [1]:
import pandas as pd
scout_car = pd.read_csv('Step 2 - Nulls filled v1.csv')
scout_car

,make_model,Body Type,Price,VAT,KM,Registration (YYYYMM),Horsepower (kW),Type,Previous Owners,Next Inspection (YYYYMM),...,Lane departure warning system,Night view assist,Passenger-side airbag,Power steering,Rear airbag,Side airbag,Tire pressure monitoring system,Traction control,Traffic sign recognition,Xenon headlights
0,Audi A1,Sedans,15770,VAT deductible,56013.0,201601.0,66.0,Used,2,202106.0,...,0,0,1,1,0,1,1,1,0,1
1,Audi A1,Sedans,14500,Price negotiable,80000.0,201703.0,141.0,Used,0,NaN,...,0,0,1,1,0,1,1,1,0,1
2,Audi A1,Sedans,14640,VAT deductible,83450.0,201602.0,85.0,Used,1,NaN,...,0,0,1,1,0,1,1,1,0,0
3,Audi A1,Sedans,14500,VAT deductible,73000.0,201608.0,66.0,Used,1,NaN,...,0,0,1,1,0,1,1,0,0,0
4,Audi A1,Sedans,16790,VAT deductible,16200.0,201605.0,66.0,Used,1,NaN,...,0,0,1,1,0,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,Renault Espace,Van,39950,VAT deductible,21213.5,201711.0,147.0,New,0,NaN,...,1,0,1,1,1,1,1,1,1,0
15915,Renault Espace,Van,39885,VAT deductible,9900.0,201901.0,165.0,Used,1,202201.0,...,1,0,1,1,0,1,1,1,1,0
15916,Renault Espace,Van,39875,VAT deductible,15.0,201903.0,146.0,Pre-registered,1,NaN,...,1,0,1,1,0,1,0,1,1,0
15917,Renault Espace,Van,39700,VAT deductible,10.0,201906.0,147.0,Pre-registered,0,NaN,...,0,0,1,1,0,1,1,0,1,0
15918,Renault Espace,Van,40999,VAT deductible,21213.5,201901.0,165.0,Demonstration,1,NaN,...,0,0,1,1,0,1,1,0,1,0

# Ensure all dtypes are what we want.

In [2]:
scout_car.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 131 columns):
 #    Column                                 Dtype
---   ------                                 -----
 0    make_model                             object
 1    Body Type                              object
 2    Price                                  int64
 3    VAT                                    object
 4    KM                                     float64
 5    Registration (YYYYMM)                  float64
 6    Horsepower (kW)                        float64
 7    Type                                   object
 8    Previous Owners                        int64
 9    Next Inspection (YYYYMM)               float64
 10   Inspection new                         int64
 11   Warranty (months)                      float64
 12   Make                                   object
 13   Model                                  object
 14   First Registration                     float64
 15   Body Color                             object
 16   Paint Type                             object
 17   Body Color Original                    object
 18   # of Doors                             float64
 19   # of Seats                             float64
 20   Model Code                             object
 21   Gearing Type                           object
 22   Displacement (cc)                      float64
 23   Cylinders                              float64
 24   Weight (kg)                            float64
 25   Drive chain                            object
 26   Fuel                                   object
 27   CO2 Emission (g CO2/km (comb))         float64
 28   Emission Class                         object
 29   Emission Label                         object
 30   Gears                                  float64
 31   Country version                        object
 32   Upholstery Material                    object
 33   Upholstery Color                       object
 34   Consumption (L /100 km) comb           float64
 35   Consumption (L /100 km) city           float64
 36   Consumption (L /100 km) country        float64
 37   Air conditioning                       int64
 38   Air suspension                         int64
 39   Armrest                                int64
 40   Automatic climate control              int64
 41   Auxiliary heating                      int64
 42   Cruise control                         int64
 43   Electric Starter                       int64
 44   Electric tailgate                      int64
 45   Electrical side mirrors                int64
 46   Electrically adjustable seats          int64
 47   Electrically heated windshield         int64
 48   Heads-up display                       int64
 49   Heated steering wheel                  int64
 50   Hill Holder                            int64
 51   Keyless central door lock              int64
 52   Leather seats                          int64
 53   Leather steering wheel                 int64
 54   Light sensor                           int64
 55   Lumbar support                         int64
 56   Massage seats                          int64
 57   Multi-function steering wheel          int64
 58   Navigation system                      int64
 59   Panorama roof                          int64
 60   Park Distance Control                  int64
 61   Parking assist system camera           int64
 62   Parking assist system self-steering    int64
 63   Parking assist system sensors front    int64
 64   Parking assist system sensors rear     int64
 65   Power windows                          int64
 66   Rain sensor                            int64
 67   Seat heating                           int64
 68   Seat ventilation                       int64
 69   Split rear seats                       int64
 70   Start-stop system                      int64
 71   Sunroof                                int64
 72   Tinted windows                         int64
 73   Wind deflector                         int64
 74   Windshield                             int64
 75   Bluetooth                              int64
 76   CD player                              int64
 77   Digital radio                          int64
 78   Hands-free equipment                   int64
 79   MP3                                    int64
 80   On-board computer                      int64
 81   Radio                                  int64
 82   Sound system                           int64
 83   Television                             int64
 84   USB                                    int64
 85   Alloy wheels                           int64
 86   Cab or rented Car                      int64
 87   Catalytic Converter                    int64
 88   Handicapped enabled                    int64
 89   Right hand drive                       int64
 90   Roof rack                              int64
 91   Shift paddles                          int64
 92   Ski bag                                int64
 93   Sliding door                           int64
 94   Sport package                          int64
 95   Sport seats                            int64
 96   Sport suspension                       int64
 97   Touch screen                           int64
 98   Trailer hitch                          int64
 99   Tuned car                              int64
 100  Voice Control                          int64
 101  Winter tyres                           int64
 102  ABS                                    int64
 103  Adaptive Cruise Control                int64
 104  Adaptive headlights                    int64
 105  Alarm system                           int64
 106  Blind spot monitor                     int64
 107  Central door lock                      int64
 108  Central door lock with remote control  int64
 109  Daytime running lights                 int64
 110  Driver drowsiness detection            int64
 111  Driver-side airbag                     int64
 112  Electronic stability control           int64
 113  Emergency brake assistant              int64
 114  Emergency system                       int64
 115  Fog lights                             int64
 116  Head airbag                            int64
 117  Immobilizer                            int64
 118  Isofix                                 int64
 119  LED Daytime Running Lights             int64
 120  LED Headlights                         int64
 121  Lane departure warning system          int64
 122  Night view assist                      int64
 123  Passenger-side airbag                  int64
 124  Power steering                         int64
 125  Rear airbag                            int64
 126  Side airbag                            int64
 127  Tire pressure monitoring system        int64
 128  Traction control                       int64
 129  Traffic sign recognition               int64
 130  Xenon headlights                       int64
dtypes: float64(16), int64(97), object(18)
memory usage: 15.9+ MB

Nothing is an object that shouldn't be. That's a good basis.

In [3]:
def detect_outliers_iqr(df):
    outlier_info = {}
    for col in df.select_dtypes(include=['number']).columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # Get outlier indices
        outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col]
        outlier_info[col] = {
            "num_outliers": len(outliers),
            "pct_outliers": round(len(outliers) / len(df) * 100, 2),
            "outlier_indices": outliers.index.tolist()
        }
    return pd.DataFrame(outlier_info).T

In [4]:
outlier_summary = detect_outliers_iqr(scout_car)
outlier_summary

,num_outliers,pct_outliers,outlier_indices
Price,479,3.01,"[713, 732, 3587, 3589, 3590, 3591, 3592, 3593,..."
KM,847,5.32,"[25, 34, 39, 43, 53, 61, 63, 64, 310, 328, 333..."
Registration (YYYYMM),0,0.0,[]
Horsepower (kW),428,2.69,"[3353, 3587, 3590, 3592, 3593, 3594, 3595, 359..."
Previous Owners,19,0.12,"[679, 972, 1290, 2729, 3269, 6103, 6406, 6669,..."
...,...,...,...
Side airbag,2716,17.06,"[9, 18, 28, 30, 50, 53, 66, 67, 69, 76, 115, 1..."
Tire pressure monitoring system,0,0.0,[]
Traction control,0,0.0,[]
Traffic sign recognition,1976,12.41,"[165, 446, 447, 506, 597, 602, 737, 1280, 1648..."
Xenon headlights,3539,22.23,"[0, 1, 4, 5, 6, 10, 11, 12, 13, 14, 18, 19, 21..."

# Let's have a look at these outliers.

# Get Dummies Here?

In [5]:
# Identify non-numeric columns
non_numerics = scout_car.select_dtypes(exclude=['number']).columns

# Apply get_dummies to non-numeric columns
dummy_df = pd.get_dummies(scout_car[non_numerics])

# Convert bools to int
dummy_df = pd.get_dummies(scout_car[non_numerics])
dummy_df = dummy_df.astype(int)

# Select numeric columns from the original DataFrame
numerics_df = scout_car.select_dtypes(include=['number'])

scout_car_with_dummies = pd.concat([numerics_df, dummy_df], axis=1)

In [6]:
scout_car_with_dummies

,Price,KM,Registration (YYYYMM),Horsepower (kW),Previous Owners,Next Inspection (YYYYMM),Inspection new,Warranty (months),First Registration,# of Doors,...,Upholstery Color_Beige,Upholstery Color_Black,Upholstery Color_Blue,Upholstery Color_Brown,Upholstery Color_Grey,Upholstery Color_Orange,Upholstery Color_Other,Upholstery Color_Red,Upholstery Color_White,Upholstery Color_Yellow
0,15770,56013.0,201601.0,66.0,2,202106.0,1,12.0,2016.0,5.0,...,0,1,0,0,0,0,0,0,0,0
1,14500,80000.0,201703.0,141.0,0,NaN,0,12.0,2017.0,3.0,...,0,0,0,0,1,0,0,0,0,0
2,14640,83450.0,201602.0,85.0,1,NaN,0,12.0,2016.0,4.0,...,0,1,0,0,0,0,0,0,0,0
3,14500,73000.0,201608.0,66.0,1,NaN,0,12.0,2016.0,3.0,...,0,1,0,0,0,0,0,0,0,0
4,16790,16200.0,201605.0,66.0,1,NaN,1,12.0,2016.0,5.0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,39950,21213.5,201711.0,147.0,0,NaN,0,16.0,2017.0,5.0,...,0,1,0,0,0,0,0,0,0,0
15915,39885,9900.0,201901.0,165.0,1,202201.0,0,16.0,2019.0,5.0,...,0,1,0,0,0,0,0,0,0,0
15916,39875,15.0,201903.0,146.0,1,NaN,1,16.0,2019.0,5.0,...,0,1,0,0,0,0,0,0,0,0
15917,39700,10.0,201906.0,147.0,0,NaN,0,16.0,2019.0,5.0,...,0,1,0,0,0,0,0,0,0,0
15918,40999,21213.5,201901.0,165.0,1,NaN,1,16.0,2019.0,5.0,...,0,0,0,1,0,0,0,0,0,0